Abilities:
  Fire:
    FlameLeap:
      Enabled: true
      NegateFallDamage: true
      Cooldown: 11000
      FireTicks: 20
      FizzleOutTime: 1500
      MaxJumps: 3
      Damage: 1.0
      XZPower: 1.3
      YPower: 0.3
    Dissipation:
      Enabled: true
      FizzleOutTime: 2000
      Controlled:
        Cooldown: 7000
      Uncontrolled:
        Cooldown: 12000
        Radius: 4.75
        Damage: 1.0
    BlazeRush:
      Enabled: true
      Controllable: false
      Cooldown: 11000
      Duration: 500
      FireTicks: 20
      Speed: 1.5
      Damage: 1.0
  Earth:
    CrustSpikes:
      Enabled: true
      Cooldown: 9000
      Damage: 2
      Range: 12
      Spikes:
        MinLength: 5
        MaxLength: 8
        MaxPitch: -45
        MinPitch: -135
        WidthRadius: 3
        Frequency: 33
    DensityAlteration:
      Enabled: true
      Cooldown: 16000
      ChargeDuration: 500
      Duration: 2000
      Radius: 7.5
    TremorWave:
      Enabled: true
      Cooldown: 15000
      Duration: 3000
      Damage: 2.0
      Radius: 2.5
      Speed: 1.5
Strings:
  Fire:
    FlameLeap:
      Description: 'FlameLeap allows the user to create a concentrated point of fire below their bodies, letting them jump mid-air. Fall damage is negated during the ability.'
      Instructions: 'Left click, this enables the ability. You can click consecutively, each using one charge.'
    Dissipation:
      Description: 'Block your enemies Fire abilities either via an uncontrolled explosion or a controlled diffusion.'
      Instructions: "Hold sneak and left click. A fire will appear in front of you; if you detect a fire ability in front of you it will dissipate. Holding sneak makes it uncontrolled."
    BlazeRush:
      Description: 'Use your FireBending to dash through your enemies and pierce them with flames.'
      Instructions: 'Hold sneak and left click.'
  Earth:
    CrustSpikes:
      Description: 'Release multiple earth spikes in various formations in front of you to hurt your enemies!'
      Instructions: 'Sneak and left click'
    DensityAlteration:
      Description: 'Densify the earth-bendable ground to suck entities towards a centre.'
      Instructions: 'Hold sneak to charge, release sneak to release.'
    TremorWave:
      Description: 'Drag the earth beneath you to create a wave, damaging entities on its path.'
      Instructions: 'Hold sneak and right click an earth-bendable block.'