Abilities:
  FlameLeap:
    Enabled: true
    NegateFallDamage: true
    Cooldown: 11000
    FireTicks: 20
    FizzleOutTime: 1500
    MaxJumps: 3
    Damage: 1.0
    XZPower: 1.3
    YPower: 0.3
  Dissipation:
    Enabled: true
    FizzleOutTime: 2000
    Controlled:
      Cooldown: 7000
    Uncontrolled:
      Cooldown: 12000
      Radius: 4.75
      Damage: 1.0
Strings:
  FlameLeap:
    Description: 'FlameLeap allows the user to create a concentrated point of fire below their bodies, letting them jump mid-air. Fall damage is negated during the ability.'
    Instructions: 'Left click, this enables the ability. You can click consecutively, each using one charge.'
  Dissipation:
    Description: 'Block your enemies Fire abilities either via an uncontrolled explosion or a controlled diffusion.'
    Instructions: 'Hold sneak and left click. A fire will appear in front of you, if you detect a fire ability in front of you it will dissipate. If the user is holding sneak it will be uncontrolled.'