name: AlmostEnoughAbilities
version: '0.1.3-SNAPSHOT'
main: me.arifkalender.projectkorra.almostenoughabilities.AlmostEnoughAbilities
api-version: '1.21'
Dependencies:
  - ProjectKorra
author: 'Kugelbltz'
